# Generated by Django 6.0.2 on 2026-02-05 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='shiftnote',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='twofactorcode',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='vote',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='vote',
            old_name='user_id',
            new_name='user',
        ),
    ]
