# Generated by Django 5.0.14 on 2026-02-06 14:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_product_base_stock_product_last_price_update_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vote',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='apps.product'),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('user', 'product')},
        ),
    ]
