# Generated by Django 5.0.14 on 2026-02-09 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_vote_created_at_alter_vote_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='note',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vote',
            name='vote',
            field=models.TextField(blank=True),
        ),
    ]
