# Generated by Django 5.0.14 on 2026-02-09 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_vote_note_vote_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='vote',
        ),
        migrations.AddField(
            model_name='vote',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
