# Generated by Django 5.0.14 on 2026-02-09 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_remove_vote_vote_vote_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='like',
            field=models.BooleanField(default=False),
        ),
    ]
