# Generated by Django 6.0.2 on 2026-02-10 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_log'),
        ('apps', '0008_order_discount'),
    ]

    operations = [
    ]
