# Generated by Django 6.0.2 on 2026-02-13 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0011_order_billing_address_order_billing_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftnote',
            name='date',
            field=models.DateField(),
        ),
    ]
